name: radcamp-ipa
channels:
  - conda-forge
  - bioconda
  - eaton-lab
dependencies:
  - python>=3.7  # the current default on mybinder
  - jupyter
  - numpy
  - pandas
  - scipy
  - numba
  - loguru
  - requests
  - msprime>=1.0
  - raxml-ng
  - raxml
  - ipyrad
  - astral3
  - scikit-learn
  - pip
  - pip:
    - git+https://github.com/eaton-lab/toytree.git@toy3#egg=toytree
    - git+https://github.com/eaton-lab/ipcoal.git@toy3#egg=ipcoal

